#!/usr/bin/env python3
"""Generate a clearly-synthetic demo shot for frontend/UI development.

This is the "hardcoded sample trajectory" referenced in the project spec
section 26 -- it exists purely so the Three.js driving range has
something physically plausible to render before any real video has
been processed. It is NOT a placeholder for real shot data: every
metric it produces is labeled EXPERIMENTAL with a note explaining it's
synthetic, and the ShotResult carries an explicit warning to that
effect. Never confuse this with scripts/process_shot.py's output.

Usage:
    python scripts/generate_sample_session.py
    (writes data/sample_sessions/sample_shot.json)
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

_REPO_ROOT = Path(__file__).resolve().parents[1]
for _pkg in ("golfie_core", "golfie_physics", "golfie_render"):
    _pkg_path = _REPO_ROOT / "packages" / _pkg
    if str(_pkg_path) not in sys.path and _pkg_path.exists():
        sys.path.insert(0, str(_pkg_path))

from golfie_core.schemas import MetricSource, MetricValue, ShotMetrics, ShotResult  # noqa: E402
from golfie_physics.models import FlightParams, simulate_from_launch_conditions  # noqa: E402
from golfie_render.threejs import build_trajectory_payload  # noqa: E402
import numpy as np  # noqa: E402

# Roughly a mid-iron-ish demo shot. These numbers are chosen to look
# reasonable on screen, not measured from anything -- that's the point.
DEMO_BALL_SPEED_MPS = 49.0  # ~110 mph
DEMO_LAUNCH_ANGLE_DEG = 16.5
DEMO_HORIZONTAL_LAUNCH_DEG = -1.5  # slightly left of target

# Assumed backspin used ONLY to drive the (experimental, spec section 13
# Phase 3) Magnus lift term so the demo arc looks like a real ball
# flight instead of a drag-only "knuckleball". This is never exposed as
# a measured/estimated spin metric -- ShotMetrics.backspin_rpm stays
# NOT_AVAILABLE below, since this build does not actually estimate spin
# from anything.
DEMO_BACKSPIN_RPM = 6200.0
_DEMO_SPIN_RAD_S = np.array([0.0, -DEMO_BACKSPIN_RPM * 2 * np.pi / 60.0, 0.0])


def build_sample_shot() -> ShotResult:
    params = FlightParams(drag_enabled=True, lift_enabled=True)
    flight = simulate_from_launch_conditions(
        ball_speed_mps=DEMO_BALL_SPEED_MPS,
        launch_angle_deg=DEMO_LAUNCH_ANGLE_DEG,
        horizontal_launch_deg=DEMO_HORIZONTAL_LAUNCH_DEG,
        params=params,
        spin_rad_s=_DEMO_SPIN_RAD_S,
    )
    simulated_points = flight.to_tracked_points(source=MetricSource.EXPERIMENTAL, confidence=0.0)

    synthetic_note = "Synthetic demo data for UI development only -- not a real golf shot."
    metrics = ShotMetrics(
        ball_speed_mps=MetricValue(value=DEMO_BALL_SPEED_MPS, source=MetricSource.EXPERIMENTAL, confidence=0.0, notes=synthetic_note),
        launch_angle_deg=MetricValue(value=DEMO_LAUNCH_ANGLE_DEG, source=MetricSource.EXPERIMENTAL, confidence=0.0, notes=synthetic_note),
        horizontal_launch_deg=MetricValue(value=DEMO_HORIZONTAL_LAUNCH_DEG, source=MetricSource.EXPERIMENTAL, confidence=0.0, notes=synthetic_note),
        carry_m=MetricValue(value=flight.carry_m, source=MetricSource.EXPERIMENTAL, confidence=0.0, notes=synthetic_note),
        total_m=MetricValue(value=flight.carry_m, source=MetricSource.EXPERIMENTAL, confidence=0.0, notes=synthetic_note + " (no ground-roll model yet, total == carry)"),
        apex_m=MetricValue(value=flight.apex_m, source=MetricSource.EXPERIMENTAL, confidence=0.0, notes=synthetic_note),
        side_deviation_m=MetricValue(value=flight.side_deviation_m, source=MetricSource.EXPERIMENTAL, confidence=0.0, notes=synthetic_note),
        # Spin/club metrics: leave NOT_AVAILABLE even in the demo, since
        # this build never claims to measure them (spec section 12).
    )

    return ShotResult(
        metrics=metrics,
        measured_points_3d=[],
        fitted_points_3d=[],
        simulated_trajectory_3d=simulated_points,
        warnings=[
            "This is a synthetic example shot for development/demo purposes only. "
            "It was generated by golfie_physics from assumed launch conditions and is "
            "not derived from any real golf shot recording.",
        ],
        is_placeholder=True,
        notes="Synthetic demo shot (not from real video data). See scripts/generate_sample_session.py.",
    )


def main() -> int:
    shot = build_sample_shot()
    payload = build_trajectory_payload("sample-demo-shot", shot, club="7-iron (synthetic demo)")

    out_dir = _REPO_ROOT / "data" / "sample_sessions"
    out_dir.mkdir(parents=True, exist_ok=True)
    out_path = out_dir / "sample_shot.json"
    out_path.write_text(json.dumps(payload, indent=2))

    print(f"Wrote {out_path}")
    print(f"  carry: {shot.metrics.carry_m.value:.1f} m, apex: {shot.metrics.apex_m.value:.1f} m")
    print(f"  trajectory points: {len(shot.simulated_trajectory_3d)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
